services:
  frontend:
    image: node:18-alpine
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    working_dir: /app
    depends_on:
      - backend
    entrypoint: sh -c "npm install && npm run dev"
    
  backend:
    image: node:18-alpine
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    working_dir: /app
    entrypoint: sh -c "npm install && npm start"