name: CI

on: [push]

jobs:
  format-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install packages
        run: npm ci

      - name: Run tests
        run: cd backend && npm test
